### ISSUE TITLE
Guys, please try a msft guidance / promptfoo integration -- good packages that we use everyday

### ISSUE THREAD

**Issue by akshhack** [BerriAI/reliableGPT#35]
I love the stuff you've built to make system level robustness. This will be super useful to me if it can also have quality level robustness. Check promptfoo and msft guidance. NVIDIA has published similar stuff as part of nemo, I think, guardrails?

**Comment by krrishdholakia** [comment]
why can't you use this with those already? we wrap the base openai endpoint, that shouldn't stop you from using testing libraries like promptfoo, etc.? 

Have you faced any errors? @akshhack
